#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = ["pytest"]
# ///
# This is AI generated code

"""Unit tests for common.crony_automate (the shared crony automation
driver borgadm and secure-archiver both build their `automate`
subcommand on)."""

import subprocess
import sys
import uuid
from pathlib import Path
from typing import Any
from unittest.mock import patch

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from common.crony_automate import CronyAutomation  # noqa: E402

_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_URL, "test-crony-automate")


class StubError(RuntimeError):
    """Stands in for a utility's own error type."""


class _Recorder:
    """Collects the driver's log / warn messages for assertions."""

    def __init__(self) -> None:
        self.logs: list[str] = []
        self.warns: list[str] = []

    def log(self, msg: str) -> None:
        self.logs.append(msg)

    def warn(self, msg: str) -> None:
        self.warns.append(msg)


def _make() -> tuple[CronyAutomation, _Recorder]:
    rec = _Recorder()
    driver = CronyAutomation(
        "stub",
        _NAMESPACE,
        "stub automate apply",
        rec.log,
        rec.warn,
        StubError,
    )
    return driver, rec


@pytest.fixture
def driver(
    tmp_path: Path, monkeypatch: Any
) -> tuple[CronyAutomation, Path, _Recorder]:
    dropin = tmp_path / "dropin"
    monkeypatch.setenv("CRONY_CONFIG_DROPIN_DIR", str(dropin))
    d, rec = _make()
    return d, dropin, rec


@pytest.fixture
def mock_run() -> Any:
    with patch("common.crony_automate.subprocess.run", autospec=True) as m:
        m.return_value = subprocess.CompletedProcess(
            args=[], returncode=0, stdout="", stderr=""
        )
        yield m


class TestPaths:
    def test_dropin_dir_prefers_dropin_env(
        self, tmp_path: Path, monkeypatch: Any
    ) -> None:
        monkeypatch.setenv("CRONY_CONFIG_DROPIN_DIR", str(tmp_path / "d"))
        monkeypatch.setenv("CRONY_CONFIG_DIR", str(tmp_path / "cfg"))
        d, _ = _make()
        assert d.dropin_dir() == tmp_path / "d"

    def test_dropin_dir_derives_from_config_dir(
        self, tmp_path: Path, monkeypatch: Any
    ) -> None:
        monkeypatch.delenv("CRONY_CONFIG_DROPIN_DIR", raising=False)
        monkeypatch.setenv("CRONY_CONFIG_DIR", str(tmp_path / "cfg"))
        d, _ = _make()
        assert d.dropin_dir() == tmp_path / "cfg" / "config"

    def test_dropin_dir_default(self, monkeypatch: Any) -> None:
        monkeypatch.delenv("CRONY_CONFIG_DROPIN_DIR", raising=False)
        monkeypatch.delenv("CRONY_CONFIG_DIR", raising=False)
        d, _ = _make()
        assert d.dropin_dir() == Path("~/.config/crony/config").expanduser()

    def test_bundle_path(
        self, driver: tuple[CronyAutomation, Path, _Recorder]
    ) -> None:
        d, dropin, _ = driver
        assert d.bundle_path() == dropin / "stub.toml"

    def test_crony_path_resolves_sibling(
        self, driver: tuple[CronyAutomation, Path, _Recorder]
    ) -> None:
        d, _dropin, _ = driver
        assert Path(d.crony_path()).name == "crony"

    def test_crony_path_raises_when_not_executable(
        self, driver: tuple[CronyAutomation, Path, _Recorder]
    ) -> None:
        d, _dropin, _ = driver
        with (
            patch(
                "common.crony_automate.os.access",
                autospec=True,
                return_value=False,
            ),
            pytest.raises(StubError, match="crony not found or not executable"),
        ):
            d.crony_path()


class TestIdentity:
    def test_job_uuid_is_deterministic(
        self, driver: tuple[CronyAutomation, Path, _Recorder]
    ) -> None:
        d, _dropin, _ = driver
        assert d.job_uuid("create") == d.job_uuid("create")
        assert d.job_uuid("create") != d.job_uuid("check")
        # Canonical lowercase UUID form (crony requires it).
        assert str(uuid.UUID(d.job_uuid("create"))) == d.job_uuid("create")

    def test_job_uuid_namespaced_by_bundle(self) -> None:
        def _noop(_m: str) -> None:
            return None

        a = CronyAutomation("alpha", _NAMESPACE, "cmd", _noop, _noop, StubError)
        b = CronyAutomation("beta", _NAMESPACE, "cmd", _noop, _noop, StubError)
        assert a.job_uuid("create") != b.job_uuid("create")

    def test_header_lines_name_the_apply_command(
        self, driver: tuple[CronyAutomation, Path, _Recorder]
    ) -> None:
        d, _dropin, _ = driver
        header = d.header_lines()
        assert header[0] == "# Generated by `stub automate apply` -- edits are"
        assert header[1] == "# overwritten on the next apply."


class TestRunCrony:
    def test_check_true_returns_zero(
        self, driver: tuple[CronyAutomation, Path, _Recorder], mock_run: Any
    ) -> None:
        d, _dropin, _ = driver
        assert d.run_crony("/bin/crony", ["apply"], check=True) == 0
        assert mock_run.called

    def test_check_true_raises_on_nonzero(
        self, driver: tuple[CronyAutomation, Path, _Recorder], mock_run: Any
    ) -> None:
        d, _dropin, _ = driver
        mock_run.return_value = subprocess.CompletedProcess([], 5, "", "")
        with pytest.raises(StubError, match="crony apply failed"):
            d.run_crony("/bin/crony", ["apply"], check=True)

    def test_check_false_returns_code(
        self, driver: tuple[CronyAutomation, Path, _Recorder], mock_run: Any
    ) -> None:
        d, _dropin, _ = driver
        mock_run.return_value = subprocess.CompletedProcess([], 5, "", "")
        assert d.run_crony("/bin/crony", ["status"], check=False) == 5


class TestApply:
    def test_writes_bundle_and_runs_apply(
        self, driver: tuple[CronyAutomation, Path, _Recorder], mock_run: Any
    ) -> None:
        d, dropin, rec = driver
        d.apply_bundle("hello\n", config_only=False)
        bundle = dropin / "stub.toml"
        assert bundle.read_text() == "hello\n"
        assert any("Wrote crony bundle" in m for m in rec.logs)
        argv = mock_run.call_args.args[0]
        assert argv[1:] == ["apply", "-b", "stub"]

    def test_config_only_skips_crony(
        self, driver: tuple[CronyAutomation, Path, _Recorder], mock_run: Any
    ) -> None:
        d, dropin, _ = driver
        with patch.object(
            d, "crony_path", autospec=True, side_effect=StubError("missing")
        ):
            d.apply_bundle("hi\n", config_only=True)
        assert (dropin / "stub.toml").exists()
        mock_run.assert_not_called()

    def test_missing_crony_leaves_no_bundle(
        self, driver: tuple[CronyAutomation, Path, _Recorder], mock_run: Any
    ) -> None:
        d, dropin, _ = driver
        with (
            patch.object(
                d, "crony_path", autospec=True, side_effect=StubError("missing")
            ),
            pytest.raises(StubError, match="missing"),
        ):
            d.apply_bundle("hi\n", config_only=False)
        assert not (dropin / "stub.toml").exists()
        mock_run.assert_not_called()


class TestReportStatus:
    def test_missing_warns_and_runs_status(
        self, driver: tuple[CronyAutomation, Path, _Recorder], mock_run: Any
    ) -> None:
        d, _dropin, rec = driver
        warned = d.report_status(lambda _t: True, config_only=False)
        assert warned
        assert any("not written yet" in m for m in rec.warns)
        assert mock_run.call_args.args[0][1:] == ["status", "-b", "stub"]

    def test_stale_warns(
        self, driver: tuple[CronyAutomation, Path, _Recorder], mock_run: Any
    ) -> None:
        d, dropin, rec = driver
        dropin.mkdir(parents=True, exist_ok=True)
        (dropin / "stub.toml").write_text("old\n")
        warned = d.report_status(lambda _t: False, config_only=False)
        assert warned
        assert any("out of date" in m for m in rec.warns)
        assert mock_run.call_args.args[0][1:] == ["status", "-b", "stub"]

    def test_current_does_not_warn(
        self, driver: tuple[CronyAutomation, Path, _Recorder], mock_run: Any
    ) -> None:
        d, dropin, rec = driver
        dropin.mkdir(parents=True, exist_ok=True)
        (dropin / "stub.toml").write_text("cur\n")
        warned = d.report_status(lambda _t: True, config_only=False)
        assert not warned
        assert any("up to date" in m for m in rec.logs)
        assert mock_run.call_args.args[0][1:] == ["status", "-b", "stub"]

    def test_config_only_skips_crony(
        self, driver: tuple[CronyAutomation, Path, _Recorder], mock_run: Any
    ) -> None:
        d, _dropin, _ = driver
        d.report_status(lambda _t: True, config_only=True)
        mock_run.assert_not_called()


class TestDestroy:
    def test_config_only_unlinks_bundle(
        self, driver: tuple[CronyAutomation, Path, _Recorder], mock_run: Any
    ) -> None:
        d, dropin, _ = driver
        dropin.mkdir(parents=True, exist_ok=True)
        (dropin / "stub.toml").write_text("x\n")
        d.destroy(config_only=True)
        assert not (dropin / "stub.toml").exists()
        mock_run.assert_not_called()

    def test_noop_when_not_applied(
        self, driver: tuple[CronyAutomation, Path, _Recorder], mock_run: Any
    ) -> None:
        d, dropin, _ = driver
        mock_run.return_value = subprocess.CompletedProcess([], 2, "", "")
        d.destroy(config_only=False)
        assert not (dropin / "stub.toml").exists()

    def test_removes_units_and_bundle(
        self, driver: tuple[CronyAutomation, Path, _Recorder], mock_run: Any
    ) -> None:
        d, dropin, _ = driver
        dropin.mkdir(parents=True, exist_ok=True)
        (dropin / "stub.toml").write_text("x\n")
        d.destroy(config_only=False)
        assert mock_run.call_args.args[0][1:] == [
            "destroy",
            "-b",
            "stub",
            "--all",
        ]
        assert not (dropin / "stub.toml").exists()

    def test_surfaces_failure_when_bundle_present(
        self, driver: tuple[CronyAutomation, Path, _Recorder], mock_run: Any
    ) -> None:
        d, dropin, _ = driver
        dropin.mkdir(parents=True, exist_ok=True)
        (dropin / "stub.toml").write_text("x\n")
        mock_run.return_value = subprocess.CompletedProcess([], 7, "", "")
        with pytest.raises(StubError, match="crony destroy failed"):
            d.destroy(config_only=False)
        assert (dropin / "stub.toml").exists()
