# This is AI generated code

"""Shared crony(1) automation driver for the repo's CLI utilities.

A utility that schedules itself through crony owns a single crony
"bundle" -- a drop-in TOML file crony reads. The bundle *content* is
per-utility (its own job set), but writing, deploying, tearing down, and
status-reporting that bundle is the same skeleton everywhere: resolve the
sibling crony executable, place the file in crony's drop-in dir, and shell
out to `crony apply | status | destroy`.

`CronyAutomation` is that skeleton, parameterized by the utility's bundle
name, UUID namespace, and its logging / error sinks. Each utility keeps
only the parts that genuinely differ: the rendered bundle text (its job
set) and a currency predicate deciding whether an on-disk bundle still
matches what the utility would generate now.
"""

import os
import subprocess
import uuid
from collections.abc import Callable
from pathlib import Path


class CronyAutomation:
    """Drives one utility's crony bundle through apply / status / destroy.

    `bundle` is the drop-in name (file `<bundle>.toml`, jobs namespaced
    `<bundle>.<op>`). `uuid_namespace` seeds the deterministic per-job
    UUIDs so re-applies reconcile in place. `apply_command` is the user-
    facing command that regenerates the bundle (named in the header and
    the drift warnings). `log` / `warn` are the utility's message sinks
    (e.g. `logger.info` / `logger.warning`, or a stderr printer) and
    `error_factory` builds the utility's own exception type so a raised
    failure maps to that utility's exit code.
    """

    def __init__(
        self,
        bundle: str,
        uuid_namespace: uuid.UUID,
        apply_command: str,
        log: Callable[[str], None],
        warn: Callable[[str], None],
        error_factory: Callable[[str], Exception],
    ) -> None:
        self.bundle = bundle
        self._uuid_namespace = uuid_namespace
        self._apply_command = apply_command
        self._log = log
        self._warn = warn
        self._error = error_factory

    def dropin_dir(self) -> Path:
        """crony's drop-in config dir, resolved exactly as crony resolves
        it (its CRONY_CONFIG_DROPIN_DIR / CRONY_CONFIG_DIR env vars, else
        the ~/.config/crony/config default) so the bundle lands where
        crony reads it. Read live per call so a redirected environment (a
        test, an override) points it elsewhere.

        The default embeds crony's own basename; it holds only while the
        sibling tool keeps that name, which `crony_path` also assumes.
        """
        dropin = os.environ.get("CRONY_CONFIG_DROPIN_DIR")
        if dropin:
            return Path(dropin)
        config_dir = os.environ.get("CRONY_CONFIG_DIR") or os.path.expanduser(
            "~/.config/crony"
        )
        return Path(config_dir) / "config"

    def crony_path(self) -> str:
        """Path to the sibling crony tool that owns the schedule.

        Located from this module's own position in the repo
        (`<repo>/src/common/crony_automate.py` -> `<repo>/bin/crony`).
        Raises the utility's error if crony isn't a usable executable, so
        apply / status / destroy fail clearly rather than mid-subprocess.
        """
        crony = Path(__file__).resolve().parent.parent.parent / "bin" / "crony"
        if not crony.is_file() or not os.access(crony, os.X_OK):
            raise self._error(f"crony not found or not executable: {crony}")
        return str(crony)

    def bundle_path(self) -> Path:
        return self.dropin_dir() / f"{self.bundle}.toml"

    def job_uuid(self, op: str) -> str:
        """Deterministic UUID for a crony job, stable across re-applies."""
        return str(uuid.uuid5(self._uuid_namespace, f"{self.bundle}-{op}"))

    def header_lines(self) -> list[str]:
        """The two-line `# Generated by ...` banner a rendered bundle
        opens with, naming the command that regenerates it."""
        return [
            f"# Generated by `{self._apply_command}` -- edits are",
            "# overwritten on the next apply.",
        ]

    def run_crony(self, crony: str, args: list[str], *, check: bool) -> int:
        """Run one crony subcommand with inherited stdio so crony's own
        output (progress, platform-grant instructions) reaches the user.
        Returns the exit code; raises the utility's error when `check`
        and the exit is nonzero."""
        proc = subprocess.run([crony, *args], check=False)
        if check and proc.returncode != 0:
            raise self._error(
                f"crony {args[0]} failed (exit {proc.returncode})"
            )
        return proc.returncode

    def apply_bundle(self, text: str, *, config_only: bool) -> None:
        """Write the bundle file, then (unless `config_only`) run
        `crony apply`. crony is resolved before the write so a missing
        crony fails cleanly instead of leaving an orphan bundle behind."""
        crony = None if config_only else self.crony_path()
        bundle = self.bundle_path()
        bundle.parent.mkdir(parents=True, exist_ok=True)
        bundle.write_text(text)
        self._log(f"Wrote crony bundle: {bundle}")
        if crony is not None:
            self.run_crony(crony, ["apply", "-b", self.bundle], check=True)

    def report_status(
        self,
        currency_check: Callable[[str], bool],
        *,
        config_only: bool,
    ) -> bool:
        """Report whether the on-disk bundle is current, then (unless
        `config_only`) show crony's per-job status table.

        `currency_check` decides whether the existing bundle text matches
        what the utility would generate now, so a bundle the utility
        deliberately customizes isn't mistaken for drift. Returns True
        when a warning (missing / stale bundle) was emitted, for the
        caller to fold into its own exit status.
        """
        crony = None if config_only else self.crony_path()
        bundle = self.bundle_path()
        warned = False
        if not bundle.exists():
            self._warn(
                f"crony bundle not written yet: {bundle} "
                f"(run '{self._apply_command}' to create it)"
            )
            warned = True
        elif not currency_check(bundle.read_text()):
            self._warn(
                f"crony bundle is out of date: {bundle} "
                f"(run '{self._apply_command}' to regenerate it)"
            )
            warned = True
        else:
            self._log(f"crony bundle is up to date: {bundle}")
        if crony is not None:
            self.run_crony(crony, ["status", "-b", self.bundle], check=False)
        return warned

    def destroy(self, *, config_only: bool) -> None:
        """Remove the deployed jobs, then delete the bundle file.

        `config_only` deletes just the bundle file, leaving any deployed
        jobs in place, and never requires crony.
        """
        bundle = self.bundle_path()
        if config_only:
            if bundle.exists():
                self._log(f"Removing crony bundle: {bundle}")
                bundle.unlink()
            return
        crony = self.crony_path()
        # `crony destroy --all` works off crony's on-disk state, so it
        # removes units and logs even when the bundle file is already
        # gone. Tolerate its nonzero exit when nothing is addressable (no
        # bundle file) -- destroying already-destroyed automation is a
        # no-op. But a present bundle file means the bundle is installed,
        # so a nonzero exit is a real failure (e.g. a running job holds
        # the lock) and is surfaced.
        rc = self.run_crony(
            crony, ["destroy", "-b", self.bundle, "--all"], check=False
        )
        if rc != 0 and bundle.exists():
            raise self._error(
                f"crony destroy failed (exit {rc}); is a {self.bundle} "
                "job currently running?"
            )
        if bundle.exists():
            self._log(f"Removing crony bundle: {bundle}")
            bundle.unlink()
